### ISSUE TITLE
Scrollbar causes misalignment of left and right image

### ISSUE THREAD

**Issue by tarmo888** [NUKnightLab/juxtapose#57] opened 2015-07-11 21:35 UTC
In preview, images are aligned perfectly, but when I copy only the URL from the embed code and paste it to new window, scrollbars appear, which causes misalignment of left and right image.
http://cdn.knightlab.com/libs/juxtapose/dev/embed/index.html?uid=70523e00-280e-11e5-91b9-0e7075bba956

When I change the window width narrower (so the vertical scrollbar dissapears) and refresh the page then left and right image are aligned perfectly again.

**Comment by JoeGermuska** [comment] 2015-07-13 15:52
Why are you copying only the URL from the embed code?

It's definitely the case that you need to control the width and height of the Juxtapose component. Normally that would be done using width and height attributes on the `<iframe>` tag. We have an open ticket about making this facet of using Juxtapose more clear in the "builder" interface. Maybe you can tell us more about what you expected to happen, etc so that we know more about what would actually be more clear.

**Comment by tarmo888** [comment] 2015-07-13 16:12
Well, embedding on a website is just one use case, but there are million other places (FB, email, IM, Twitter etc) where people could just share a link. Also, it would be nice, if it would have OpenGraph tags and twittercards in meta.

**Comment by JoeGermuska** [comment] 2015-07-13 16:43
We recognize the appeal of opengraph, etc, but also feel like that blows open the complexity of the authoring tool. A juxtapose doesn't have a title. The `og:image` you'd want is probably not either of the actual images but rather something that telegraphed that the page was a slider, so we'd have to create one of those. Pretty soon, people have to have a Juxtapose account, log in, manage their previously created "juxtaposes" and so forth.

So I won't say "never", but I don't expect us to pick up that problem in the near future.

**Comment by tarmo888** [comment] 2015-07-13 22:41
* og:title - can be generated from the filenames of the source images like "Sochi_11April2005.jpg vs Sochi_22Nov2013.jpg" or whatever.
* og:image - multiple images can be listed, so user can pick either left or right image. There is already 4 optional fields in authoring tool, wouldn't hurt to add one more optional thumbnail image.

But that's not the issue, **the issue is that two images are not aligned when opened in new window because of the scrollbar**, but I guess "closed" means "won't fix".

What keeps people wanting for an account management right now? Keeping the project less-shareable? Pasting a link to somewhere is main way how people share stuff, not embedding.

And those who want an account management, just simply say that it's like url shortener - want to edit previously created juxtapose then just create a new juxtapose.

**Comment by duner** [comment] 2015-07-13 22:54
I'll take a look at the image alignment in that situation. It looks like adding `overflow-y: scroll;` to the `html` tag kinda solves the problem—but I'll need to test it in an embedded post to make sure it doesn't mess up that use case (which is our primary use case for now).

**On the open graph stuff:** I think that the idea of "one more optional field" in the admin might open the door to a lot of options we don't necessarily want to support. What if people want to edit og:description or want to change the title of the page? What if they want to add custom Google Analytics? You're more than welcome to fork the project and try implementing some of this stuff, but I don't think it's on our roadmap for the near future.

**Comment by JoeGermuska** [comment] 2015-07-14 20:51
@duner can you check out this new `maximize-iframe` branch and make sure it's not crazy? It's more for #54 and a side convo I had with @ryanpitts about how juxtapose works in iframes

**Comment by JoeGermuska** [comment] 2015-07-21 21:35
There are no scrollbars anymore, but looking at http://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=70523e00-280e-11e5-91b9-0e7075bba956 (from above), there's a definite flaw in the "maximize" strategy. The images align if the browser window is 640x426, but at other dimensions, the alignment of the images is wrong.

Also, the maximizing uses the image heights, so the credits aren't seen. That doesn't bother me so much, as I kind of think the credits should be outside of a Juxtapose anyway, to save the trouble of i18n for the labels. Credits outside of the Juxtapose are at odds with the usecase of a standalone URL, but I'm still not persuaded that that's an important use case.

@hbillings  this may overlap with stuff you're looking at in #54

**Comment by Andytizer** [comment] 2015-08-11 07:27
It would be great if you could view the comparisons in a fullscreen window. I want to be able to copy the uid view and see things in more detail.

**Comment by JoeGermuska** [comment] 2015-08-11 14:26
@Andytizer pull requests are welcome! At the moment, other projects are ahead of Juxtapose on our priority list, but we will keep this ticket open until such time as either we can schedule work on it or someone might fix it and contribute the fix back.  *Vive le Open Source!*

**Comment by archgirl** [comment] 2015-08-19 18:12
In the preview my Juxtapose has no scrollbars but once the iframe is pasted they appear. I tried resizing the iframe, adding padding, margin, etc. and they will not go away. I've also tried removing the image credits. Are there any suggestions to make them go away and still keep the image credits?

Here's the iframe... (can't figure out markdown so spaces have been added for the iframe code to appear)

< iframe class="juxtapose" width="640" height="426" src="https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=983d61f4-469c-11e5-bf72-0e7075bba956" >< /iframe >

![screen shot 2015-08-19 at 12 07 19 pm](https://cloud.githubusercontent.com/assets/13355243/9364676/dcd81052-466a-11e5-9c18-e29e0415400c.png)

**Comment by hbillings** [comment] 2015-08-19 19:59
@archgirl When you say you tried "resizing the iframe," do you mean that you changed the height attribute in the iframe? From the screenshot it seems the width and height values (`width="640" height="426"`) are not great enough to accommodate your images.

**Comment by archgirl** [comment] 2015-08-19 22:10
I increased the width and height all the way to 950 (the Max of my
container) and the scrollbars persist. I'm not sure why it's behaving so
strange. I tried smaller versions of the images (they are CC on flickr) and
the scrollbars still happened.

**Comment by hbillings** [comment] 2015-08-19 22:13
@archgirl And, just to cover all the bases, the smaller versions of the images were indeed smaller than the width and height as specified in the `iframe` tag (not with CSS width and height properties)? If so, drop me the image links, if you would please, and I'll see if I can reproduce.

**Comment by hbillings** [comment] 2015-09-04 17:47
Closing to open more specific tix.

**Closed by hbillings** 2015-09-04 17:47 UTC
