### ISSUE TITLE
Vertical doesn't work in Firefox

### ISSUE THREAD

**Issue by tomByrer** [NUKnightLab/juxtapose#85] opened 2016-02-12 17:40 UTC
FxDevEd, OSX
Switching to Vertical in demo (including using [Update] button) doesn't work.  Works fine in Chrome on same machine.

Thanks for your fine work!

**Comment by duner** [comment] 2016-02-19 20:04
I just downloaded the latest version of Firefox Developer Edition on OSX (46.0a2 (2016-02-19)) and am not seeing this problem. I'm also not seeing it in the general release version of Firefox, so I'm going to go ahead and close this issue as we're not super concerned about supporting cutting edge, nightly release, browsers.

If you are still seeing problems, I can reopen the issue.

**Closed by duner** 2016-02-19 20:04 UTC
Labels: wontfix

**Comment by complutense** [comment] 2016-07-21 21:39
Hi
Thank you for this; it looks terrific and will be very useful for me.
However...
I am using the general release of Firefox, v 47.0
The vertical mode does not work: the slider does not move on dragging.
I see no errors in the JS console.
Pale Moon Version: 26.3.0 (x64) does not work either.
Chrome works fine.
MSIE 11 does not slide either, and the bottom image is not displayed.
(all under Win7)

Thanks for any hints

**Comment by complutense** [comment] 2016-07-22 10:24
More testing of Vertical, under Win10:
Firefox v. 47.0.1 fails: no dragging, clicking on the arrows does nothing either.
Pale Moon v. 26.2.2 (x64) fails.
MS IE11 fails: no dragging, bottom image not displayed
MS Edge works fine.
Opera v. 38.0.2220.41 works fine.

**Comment by enricobattocchi** [comment] 2016-11-15 13:32
Doesn't work on Firefox 49.0.2 on Ubuntu.
Demo: if set vertical, neither dragging nor clicking on a point in the image works..
WordPress website using juxtapose v1.1.7: clicking doesn't work, trying to drag results in slider jumping to the lowest position, then dragging up is lagging and doesn't go beyond half height of the image.
No error in JS console.

**Comment by enricobattocchi** [comment] 2016-11-15 13:56
I tried a bit of debug, looks like the return value of getTopPercent is always greater than 100 (talking about demo page; in Chromium it's always less than 100).
Looks like the problem is that document.body.scrollTop (line 227) always returns 0. It seems that document.documentElement.scrollTop is the right standard, but WebKit uses document.body.
Here is an explanation and a possible fix:
https://miketaylr.com/posts/2014/11/document-body-scrolltop.html
